trigger:
  - preview

pool: default

jobs:
  - job: Test
    displayName: ProceduralToolkit Test
    steps:
      - task: PowerShell@2
        inputs:
          filePath: 'testrun.ps1'
          arguments: '-testType Unit -batchMode'
        displayName: Unit Tests
  
      - task: PowerShell@2
        inputs:
          filePath: 'testrun.ps1'
          arguments: '-testType UI -batchMode'
        displayName: UI Tests
  
      - task: PowerShell@2
        inputs:
          filePath: 'testrun.ps1'
          arguments: '-testType E2E -batchMode'
        displayName: E2E Tests
  
  - job: PushToMaster
    displayName: Push ProceduralToolkit To Master
    dependsOn: Test
    steps:
      - checkout: self
        clean: true
        persistCredentials: true
      
      - script: |
          git branch -d master
          git checkout --track origin/master
          git merge origin/preview
          git push
        displayName: Push

