trigger:
  - preview

pool: default

jobs:
  - job: Test
    displayName: ProceduralToolkit Test
    steps:
      - task: PowerShell@2
        inputs:
          filePath: 'testrun.ps1'
          arguments: '-testType Unit -batchMode'
        displayName: Unit Tests
  
      - task: PowerShell@2
        inputs:
          filePath: 'testrun.ps1'
          arguments: '-testType UI -batchMode'
        displayName: UI Tests
  
      - task: PowerShell@2
        inputs:
          filePath: 'testrun.ps1'
          arguments: '-testType E2E -batchMode'
        displayName: E2E Tests

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: Unit.log
          artifactName: Logs
        displayName: Publish Unit tests log

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: UI.log
          artifactName: Logs
        displayName: Publish UI tests log
      
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: E2E.log
          artifactName: Logs
        displayName: Publish E2E tests log

  - job: PushToMaster
    displayName: Push ProceduralToolkit To Master
    dependsOn: Test
    steps:
      - checkout: self
        clean: true
        persistCredentials: true
      
      - script: |
          git branch -D master
          git checkout --track origin/master
          git merge origin/preview
          git push
        displayName: Push
