trigger:
  - preview

steps:
  - checkout: self

  - task: PowerShell@2
    inputs:
      filePath: 'testrun.ps1'
      arguments: '-testType Unit'
    displayName: 'Unit Tests'
  
  - task: PowerShell@2
    inputs:
      filePath: 'testrun.ps1'
      arguments: '-testType UI'
    displayName: 'UI Tests'
  
  - task: PowerShell@2
    inputs:
      filePath: 'testrun.ps1'
      arguments: '-testType E2E'
    displayName: "E2E Tests"
  
  - script: |
      git clean
      git add --renormalize .
      git checkout master
      git merge preview
      git push
    displayName: "Push to master"
