trigger:
  - preview

pool: default

resources:
 repositories:
   - repository: ProceduralToolkit
     type: github
     name: dropil/ProceduralToolkit
     ref: refs/heads/preview
     endpoint: dropik

steps:
  - checkout: ProceduralToolkit

  - task: PowerShell@2
    inputs:
      filePath: 'testrun.ps1'
      arguments: '-testType Unit -batchMode'
    displayName: 'Unit Tests'
  
  - task: PowerShell@2
    inputs:
      filePath: 'testrun.ps1'
      arguments: '-testType UI -batchMode'
    displayName: 'UI Tests'
  
  - task: PowerShell@2
    inputs:
      filePath: 'testrun.ps1'
      arguments: '-testType E2E -batchMode'
    displayName: "E2E Tests"
  
  - script: |
      git clean
      git add --renormalize .
      git checkout master
      git merge preview
      git push
    displayName: "Push to master"
