trigger:
  - development

pool: default

stages:
  - stage: mono
    displayName: ProceduralToolkit Mono testing
    jobs:
    - job: UnitTest
      displayName: ProceduralToolkit Unit Test
      steps:
        - task: PowerShell@2
          inputs:
            filePath: 'testrun.ps1'
            arguments: '-testType Unit -batchMode -settings "mono.json"'
          displayName: Execute tests
              
        - task: PublishTestResults@2
          inputs:
            testResultsFormat: 'NUnit'
            testResultsFiles: 'TestResults/results.xml'
            failTaskOnFailedTests: true
          displayName: Publish test results

    - job: IT
      displayName: ProceduralToolkit Integration Test
      dependsOn: UnitTest
      steps:
        - task: PowerShell@2
          inputs:
            filePath: 'testrun.ps1'
            arguments: '-testType IT -batchMode -settings "mono.json"'
          displayName: Execute tests
        
        - task: PublishTestResults@2
          inputs:
            testResultsFormat: 'NUnit'
            testResultsFiles: 'TestResults/results.xml'
            failTaskOnFailedTests: true
          displayName: Publish test results

    - job: E2ETest
      displayName: ProceduralToolkit E2E Test
      dependsOn: IT
      steps:
        - task: PowerShell@2
          inputs:
            filePath: 'testrun.ps1'
            arguments: '-testType E2E -batchMode -settings "mono.json"'
          displayName: Execute tests
        
        - task: PublishTestResults@2
          inputs:
            testResultsFormat: 'NUnit'
            testResultsFiles: 'TestResults/results.xml'
            failTaskOnFailedTests: true
          displayName: Publish test results
          
    - job: PublishLogs
      displayName: ProceduralToolkit Publish Test Logs
      dependsOn: E2ETest
      steps:
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: Logs
            artifactName: MonoLogs
          displayName: Publish test logs

  - stage: il2cpp
    displayName: ProceduralToolkit IL2CPP testing
    jobs:
      - job: UnitTest
        displayName: ProceduralToolkit Unit Test
        steps:
          - task: PowerShell@2
            inputs:
              filePath: 'testrun.ps1'
              arguments: '-testType Unit -batchMode -settings "il2cpp.json"'
            displayName: Execute tests
                
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'NUnit'
              testResultsFiles: 'TestResults/results.xml'
              failTaskOnFailedTests: true
            displayName: Publish test results

      - job: IT
        displayName: ProceduralToolkit Integration Test
        dependsOn: UnitTest
        steps:
          - task: PowerShell@2
            inputs:
              filePath: 'testrun.ps1'
              arguments: '-testType IT -batchMode -settings "il2cpp.json"'
            displayName: Execute tests
          
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'NUnit'
              testResultsFiles: 'TestResults/results.xml'
              failTaskOnFailedTests: true
            displayName: Publish test results

      - job: E2ETest
        displayName: ProceduralToolkit E2E Test
        dependsOn: IT
        steps:
          - task: PowerShell@2
            inputs:
              filePath: 'testrun.ps1'
              arguments: '-testType E2E -batchMode -settings "il2cpp.json"'
            displayName: Execute tests
          
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'NUnit'
              testResultsFiles: 'TestResults/results.xml'
              failTaskOnFailedTests: true
            displayName: Publish test results
            
      - job: PublishLogs
        displayName: ProceduralToolkit Publish Test Logs
        dependsOn: E2ETest
        steps:
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: Logs
              artifactName: IL2CPPLogs
            displayName: Publish test logs