name: CI

on:
  push:
    branches:
      - 'feature/*'
      - 'fix/*'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: jungwinter/split@v1
        id: feature-name
        with:
          msg: ${{ github.ref }}
          seperator: '/'

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PR }}
          commit-message: "[${{ steps.feature-name.outputs._2 }}] ${{ steps.feature-name.outputs._3 }}"
          branch: ${{ github.ref }}
          delete-branch: true
          base: development
          title: "[${{ steps.feature-name.outputs._2 }}] ${{ steps.feature-name.outputs._3 }}"
          labels: ${{ steps.feature-name.outputs._2 }}