name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  split-upm:
    name: Split UPM Branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: development
    
    - uses: jungwinter/split@v1
      id: current_ref
      with:
        msg: ${{ github.ref }}
        seperator: '/'

    - name: Split UPM Branch
      run: |
        git subtree split -P "$PKG_ROOT" -b main
        git push -f -u origin main
      env:
        PKG_ROOT: Packages/com.daniil-ryzhkov.proceduraltoolkit

    - name: Transfer Tag to Main Branch
      run: |
        git config --global user.name 'github-bot'
        git config --global user.email 'github-bot@users.noreply.github.com'
        git checkout main
        git push origin --delete ${{ github.ref }}
        git tag -fa ${{ steps.current_ref.outputs._2 }} -m "Release ${{ steps.current_ref.outputs._2 }}"
        git push origin ${{ github.ref }}

  create-release:
    name: Create Release
    needs: [split-upm]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: README.md
          draft: false
          prerelease: false
