name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  split-upm:
    name: split upm branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: master
    - name: split upm branch
      run: |
        git subtree split -P "$PKG_ROOT" -b main
        git push -f -u origin main
      env:
        PKG_ROOT: Packages/com.daniil-ryzhkov.proceduraltoolkit
    - name: transfer tag to upm branch
      run: |
        git checkout main
        git push origin --delete ${{ github.ref }}
        git tag -fa ${{ github.ref }} -m "Release ${{ github.ref }}"
        git push origin ${{ github.ref }}

  create-release:
    name: Create Release
    needs: [split-upm]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: README.md
          draft: false
          prerelease: false
