name: upm
on:
  push:
    tags:
      - 'v*'
jobs:
  split-upm:
    name: split upm branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: master
    - name: split upm branch
      run: |
        git branch -D upm &> /dev/null || echo upm branch not found
        git subtree split -P "$PKG_ROOT" -b upm
        git push -f -u origin upm
      env:
        PKG_ROOT: Packages/com.daniil-ryzhkov.proceduraltoolkit
  create-release:
    name: Create Release
    needs: [split-upm]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: upm
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: README.md
          draft: false
          prerelease: false
